# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0002_auto_20190227_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='etika',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
