# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0003_auto_20190227_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='etika',
        ),
        migrations.AddField(
            model_name='member',
            name='ethnic',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['address', 'name'], name='app_transac_address_d63d10_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['ethnic'], name='app_transac_ethnic_9d107b_idx'),
        ),
    ]
