# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_transaction', '0005_remove_group_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('name', 'address'), ('address', 'ethnic')]),
        ),
    ]
